version: "3.9"

services:
  db:
    image: postgres:16
    container_name: bitel_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: bitel
      POSTGRES_PASSWORD: bitel
      POSTGRES_DB: bitel_mvp
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
    container_name: bitel_server
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://bitel:bitel@db:5432/bitel_mvp?schema=public
      JWT_SECRET: cambia_esto
      JWT_EXPIRES_IN: 1d
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npm run seed && node dist/main.js"

  web:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: /api/v1
    container_name: bitel_web
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  db_data:
